name: Python CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installer les dépendances système requises
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-glx
      - name: Installer les dépendances Python
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Vérifier la version de numpy
        run: pip install 'numpy<2'
      - name: Lancer les tests unitaires
        run: pytest tests/